language: python
python:
- '2.7'
env:
- DJANGO_SETTINGS_MODULE=django_bucketlist.settings.test
install:
- pip install --upgrade pip
- pip install --upgrade virtualenv
- pip install -r requirements.txt
- pip install coveralls
- npm install bower
script:
- bower install --save --settings=django_bucketlist.settings.test
- python manage.py collectstatic --noinput --settings=django_bucketlist.settings.test
- coverage run manage.py test
after_success:
- coveralls

deploy:
  provider: heroku
  api_key:
    secure: EsdRQqEu3D/CQEK+WB3ZOBsUf/7SietaDPJ4dqKGMjCpGBjKDhjhUcg0NJmtT/4bucfGo4vlk6AuLvhxiVHuat+I90D2gAYadooaVEVP6GzDGmJTfqg6RlUlRPGTHzKy+QVHYNk8yz7GGmstH8I59lWhs6dDYLf324b+1Hgsfe/aWgAqmsDAVaoPDjI96PimoU3uTcg16ZZXxLYH0oaF4PykqcsqwbQzKFQvXD2WpvwGYL6rlPQT/SBE+Lg5U1SyWVh5mZMvqP+rYWZg33DlXaR0pWvLqjOytQRfAMI72at+MVzj+SeuVvcIuXvM0JeOG52a2wXDcJIru7IAr3ncaIljNpSky7yypON+DjmD75WGspewrSrdzGAgOE+JMw6LaOt3A2b8kb8+/hRPmhc8Debt1GF3evMZn28g29VtRpeZ8S6OQ2VOsyRFZrRAV0L26iaoWn26YUIly1QIPGKFJqDPDSl+Eofs6xwU/H1BHp2UsW+PoyR/Ng23D5VM2TF9Jlum5Jw/a0qeWK/zCutTU4GGOCCrfEZYqpMssebVspJT/hI2x+o7y1yET1hU4IL/Y0HOO0J8kB7VbJOVzLld1jAKlKKv2QMjaJySc8mjdX0J6hf7piMX7A4ZCknS7Ry32mna1MloVnvt0hAdfwiAZ0yE2UK6IP/B5Z64CqjSCL8=
  app: django-bucketlist
  on:
    repo: andela-ashuaib/django-bucketlist
  run:
    - "export DJANGO_SETTINGS_MODULE=django_bucketlist.settings.production"
    - "python manage.py collectstatic --noinput"
    - "python manage.py makemigrations"
    - "python manage.py migrate"