language: python
python:
- '2.7'
env:
- DJANGO_SETTINGS_MODULE=django_bucketlist.settings.test
install:
- pip install --upgrade pip
- pip install --upgrade virtualenv
- pip install -r requirements.txt
- pip install coveralls
- npm install bower
script:
- bower install --settings=django_bucketlist.settings.test
- python manage.py collectstatic --noinput --settings=django_bucketlist.settings.test
- coverage run manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: 3fUP9yiBa8P7GM/4hkyEhJfamqBDYMN7ykvPt1k8EK4LNm67UKpr5WMvxiCD5rdpzteB978ERFdnHxy+/6zzWxitIVxP51eRjP8T2ACtfW6VhVY9ClX6HYxCG87R1R3fIRA98t6hX3dcTB6v4GkL2VhHD+pzu56hxmwn+nJJZemDCAQ7vaqc/ADhPy//o3G8rhXaak3EbZ9dyUSj/Iw1bXd0csf4qnWPRgzyTBCj5qY/a05CBew5Zu1N45n0vqDqoDx7sW0ZuuVR8V59Cazd4/r/VYUT0Xihiy6/KS0L5JhzfQbDp668DHml0HOyTEbTi9jjEftiFW/Bu9Y+C1XJrYtA825UiZHz7LnFKDxFFvp0bQIGWlNq9wCYTnjFRmokgySbI5j0DxElPSvRVdxw7kfftH1PCMDVs7WtMkPxyN56RphzCzWkg5L+5W01mAkeM7O5nMatuthfrV6hgWJ7+NR8fR+kcI1ewDpK3M5vj0Lta+PexCXT3SeXNU6QDt3ID19t0r2hBxt0+6bsa0+NgFPZyRChwczhEf9/UFCdV/+1nQiHAMvXov8ReAmYggsmeA68BWVDuvMT7IBLsQRfTMIPqU8OAkTEDIQFb30DzUtkeYjbM/eta3xO85+geWU9+/eqk7LtF9Yl67Kn9fjQHRC4ac/kGujznVqh0ekyCoM=
  app: bucketlist-app
  on:
    repo: andela-ashuaib/django-bucketlist
  run:
    - "export DJANGO_SETTINGS_MODULE=djangobucketlist.settings.production"
    - "python djangobucketlist/manage.py collectstatic --noinput"
    - "python djangobucketlist/manage.py makemigrations"
    - "python djangobucketlist/manage.py migrate"
